version: '3.6'


services:
  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  db_data:
