[tool.black]
line-length = 120
target-version = ['py39']
skip-string-normalization = true

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 120
lines_after_imports = 2

[tool.pylint.'MESSAGES CONTROL']
max-line-length = 120
extension-pkg-whitelist = "pydantic"


[pytest]
testpaths = [
    "tests",
]
log_cli=true
log_level=0
